import { config } from "dotenv";
config();
export const atlas = process.env.DBURL;
export const appdb =  process.env.DB;
export const port = process.env.PORT;
export const graphql = process.env.GRAPHQLURL;
export const userCollection = process.env.USERCOLLECTION;
export const recipeCollection = process.env.RECIPECOLLECTION;
export const userRecipeCollection = process.env.USER_RECIPECOLLECTION;
export const userIngredientCollection = process.env.USER_INGREDIENTCOLLECTION;
export const userFavouriteCollection = process.env.USER_FAVOURITES_COLLECTION;
export const sharedRecipeCollection = process.env.RECIPES_SHARED_COLLECTION;
export const aws_access_key = process.env.AWS_SW3_ACCESS_KEY;
export const aws_secret_key = process.env.AWS_SW3_SECRET_ACCESS_KEY;
export const bucket_region = process.env.BUCKET_REGION;
export const bucket_name = process.env.BUCKET_NAME;
export const edge_secret_key = process.env.EDGE_STORE_SECRET_KEY;
export const edge_access_key = process.env.EDGE_STORE_ACCESS_KEY;
export const recipeReviewCollection = process.env.RECIPES_REVIEWS_COLLECTION;
export const walmart_api_key = process.env.WALMART_API_KEY;
export const walmart_api_host = process.env.WALMART_API_HOST;
export const ingredientCollection = process.env.INGREDIENTCOLLECTION;
export const endPoint = process.env.END_POINT;
export const mixmate_domain = process.env.MIXMATE_DOMAIN;