import { Inter, Roboto, Noto_Sans } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { API_ROUTES } from "./_utilities/_client/constants";
import RootPage from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MixMate",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider
        loginUrl={API_ROUTES.login}
        profileUrl={API_ROUTES.userJson}
      >
        <body className={inter.className}>
          <RootPage>{children}</RootPage>
        </body>
      </UserProvider>
    </html>
  );
}
