import { Inter } from "next/font/google";
import "./globals.css";
import MenuBar from "@/app/(components)/MenuBar";
import { Provider } from "react-redux";
import ReduxProvider from "../redux/provider";
import RootPage from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RootPage>{children}</RootPage>
      </body>
    </html>
  );
}
